#!/usr/bin/env python3
"""Session 41 TASK 6: build demo_s41/INDEX.md from the two batches' results.tsv files.

Reads each trial's own meta.json rather than trusting the batch log lines, so the index
cannot drift from what was actually recorded on disk.
"""
import csv
import json
import os
import sys

ROOT = "/mnt/ssd/Social_Navigation/trial_outputs/demo_s41"


def load(tsv):
    if not os.path.exists(tsv):
        return []
    with open(tsv) as f:
        # out_dir must be present: the batch scripts append a bare "BATCH.. COMPLETE" sentinel
        # line, which DictReader otherwise yields as a row with every other field None.
        return [r for r in csv.DictReader(f, delimiter="\t") if r.get("out_dir")]


def meta_of(out_dir):
    p = os.path.join(out_dir, "meta.json")
    if not os.path.exists(p):
        return {}
    try:
        return json.load(open(p))
    except Exception:
        return {}


def rel(p):
    return os.path.relpath(p, ROOT) if p.startswith(ROOT) else p


def ped_travel(out_dir):
    """(net displacement, path length) of the pedestrian, from frames.csv.

    Net vs path length is the whole point of the screen: a MOVING clip should show both
    large; a STATIONARY clip should show both near zero. Large path length with near-zero
    net displacement means the character is churning in place -- i.e. foot-sliding or
    drifting -- which is exactly what question 3 of the survival screen is looking for.
    """
    p = os.path.join(out_dir, "frames.csv")
    if not os.path.exists(p):
        return None, None
    xs, zs = [], []
    with open(p, newline="") as f:
        for row in csv.DictReader(f):
            try:
                xs.append(float(row["pedestrian_x"]))
                zs.append(float(row["pedestrian_z"]))
            except (ValueError, KeyError):
                continue
    if len(xs) < 2:
        return None, None
    net = ((xs[-1] - xs[0]) ** 2 + (zs[-1] - zs[0]) ** 2) ** 0.5
    path = sum(((xs[i] - xs[i - 1]) ** 2 + (zs[i] - zs[i - 1]) ** 2) ** 0.5
               for i in range(1, len(xs)))
    return net, path


def artifacts(out_dir):
    """Which deliverables actually exist -- the _ov clip and contact sheet the ticket asks for."""
    names = ["pov_full_ov.mp4", "pov_near_00_ov.mp4", "contact_sheet_full.png", "contact_sheet_00.png"]
    return [n for n in names if os.path.exists(os.path.join(out_dir, n))]


def census_valid(rows):
    """Rows admissible to a SAFETY census -- keyed on GEOMETRY gates, not the exit code.

    The content gate fails on legitimately extreme-close-pass footage: w1.2_02 exited 1 on the
    content gate alone, with trigger-speed and approach both green and a perfectly valid
    min_dist of 0.341m -- a BREACH. Filtering on exit code would silently drop breaches and bias
    the safety numbers optimistically, the exact failure this project's N>=5 worst-observed rule
    exists to prevent. Trigger-speed and approach failures ARE excluded: a robot that never moved,
    or a wrong spawn distance, makes min_dist meaningless rather than merely ugly.
    """
    keep = []
    for r in rows:
        if r.get("min_dist") in (None, "", "NA"):
            continue
        m = meta_of(r["out_dir"])
        if m.get("triggerSpeedGateOk") is False or m.get("approachGateOk") is False:
            continue
        keep.append(r)
    return keep


def worst(rows):
    vals = [float(r["min_dist"]) for r in census_valid(rows)]
    return min(vals) if vals else None


# 6.1 screening verdicts, from known_issues/S41_mixamo_screen61.md. The screen's real
# question is whether the animation is visually correct -- exit=0 and safetyLabel=safe say
# nothing about that, so they must never be presented as the verdict. Four clips fail: the
# stationary ones translate ~14m (the ticket's predicted "idle 平移"), and
# Stroke_Shaking_Head is additionally not grounded, which is the more severe defect.
SCREEN61_FAIL = {
    "Sitting":             "glide",
    "Standing_Arguing":    "glide",
    "Talking_standing":    "glide",
    "Stroke_Shaking_Head": "not-grounded",
}


def main():
    screen = load(os.path.join(ROOT, "screen61", "results.tsv"))
    corridor = load(os.path.join(ROOT, "corridor62", "results.tsv"))

    out = ["# Session 41 -- demo_s41", "",
           "Generated by `tools/s41_make_index.py`. Every number is read back from each trial's",
           "own `meta.json`, not from the batch log.", ""]

    if screen:
        out += ["## 6.1 Survival screen (N=2, open field, no corridor)", "",
                "Four questions per clip: does the character move, does the clip play, does it",
                "foot-slide, is the facing right. `net_m` is straight-line start-to-end",
                "displacement and `path_m` the summed per-frame path length, both from",
                "`frames.csv`. Together they answer the first three objectively: a moving clip",
                "shows both large, a stationary one both near zero, and large path with near-zero",
                "net means the character is churning in place (foot-slide / drift).", "",
                "> **`exit=0` and `label=safe` are NOT this screen's verdict.** Every one of the 18",
                "> runs exited cleanly and every one is labelled `safe`; four clips are nonetheless",
                "> broken. Read the `screen` column, not `exit`/`label`. Full diagnosis, including",
                "> the measurement that exposed it and the suspected fixes:",
                "> [`known_issues/S41_mixamo_screen61.md`](../../../social_sim_unity/known_issues/S41_mixamo_screen61.md).",
                "",
                "The four FAIL clips are stationary animations whose character translates ~14m -- the",
                "same `net_m` as a running clip, which is why `translates` is a defect for them, not a",
                "pass. `Stroke_Shaking_Head` fails additionally and more severely: it is not grounded.",
                "**These four did not advance to 6.2.**", "",
                "| clip | run | screen | exit | min_dist | label | net_m | path_m | verdict | artifacts |",
                "|---|---|---|---|---|---|---|---|---|---|"]
        for r in screen:
            m = meta_of(r["out_dir"])
            net, path = ped_travel(r["out_dir"])
            fail_reason = SCREEN61_FAIL.get(r["clip"])
            if net is None:
                verdict, netf, pathf = "NO DATA", "NA", "NA"
            else:
                netf, pathf = "{:.2f}".format(net), "{:.2f}".format(path)
                if path < 0.5:
                    verdict = "static (holds station)"
                elif net < 0.5 <= path:
                    verdict = "CHURNS IN PLACE"
                elif path > 0 and net / path < 0.5:
                    verdict = "wanders"
                elif fail_reason == "not-grounded":
                    verdict = "translates, NOT GROUNDED (FAIL)"
                elif fail_reason:
                    verdict = "glides (FAIL)"
                else:
                    verdict = "translates"
            out.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
                r["clip"], r["run"],
                "**FAIL** ({})".format(fail_reason) if fail_reason else "pass",
                r["exit"], r.get("min_dist", "NA"),
                m.get("safetyLabel", r.get("safety_label", "NA")),
                netf, pathf, verdict,
                ", ".join(artifacts(r["out_dir"])) or "none"))
        out.append("")

        by_clip = {}
        for r in screen:
            by_clip.setdefault(r["clip"], []).append(r)
        out += ["### Per-clip worst-of-N", "", "| clip | N valid | worst min_dist |", "|---|---|---|"]
        for clip, rows in sorted(by_clip.items()):
            w = worst(rows)
            n = len(census_valid(rows))
            out.append("| {} | {} | {} |".format(clip, n, "{:.3f}".format(w) if w else "NA"))
        out.append("")

    if corridor:
        out += ["## 6.2 Corridor width sweep (N=5 per width)", "",
                "> **This sweep used plain `business_male_01` with NO `--mixamo-clip`.** None of the",
                "> 5 passing Mixamo clips were exercised in a corridor -- the asset dimension of the",
                "> ticket's 6.2 matrix was dropped for budget (full matrix 5 clips x 4 widths x N=5 =",
                "> 100 trials). This measures the corridor, not the new assets. See the Session 41",
                "> report's scope section.",
                "",
                "| width | run | exit | min_dist | label |", "|---|---|---|---|---|"]
        for r in corridor:
            m = meta_of(r["out_dir"])
            out.append("| {} | {} | {} | {} | {} |".format(
                r["width"], r["run"], r["exit"], r.get("min_dist", "NA"),
                m.get("safetyLabel", r.get("safety_label", "NA"))))
        out.append("")

        by_w = {}
        for r in corridor:
            by_w.setdefault(r["width"], []).append(r)
        out += ["### Worst-of-5 per width (the safety claim)", "",
                "| width | N valid | worst min_dist | label at worst |", "|---|---|---|---|"]
        for w_, rows in sorted(by_w.items(), key=lambda kv: -float(kv[0])):
            wv = worst(rows)
            n = len(census_valid(rows))
            lab = ("safe" if wv >= 0.5 else "marginal" if wv >= 0.36 else "breach") if wv else "NA"
            out.append("| {} | {} | {} | {} |".format(
                w_, n, "{:.3f}".format(wv) if wv else "NA", lab))
        out.append("")

    path = os.path.join(ROOT, "INDEX.md")
    os.makedirs(ROOT, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", path, "({} screen rows, {} corridor rows)".format(len(screen), len(corridor)))


if __name__ == "__main__":
    sys.exit(main())
