#!/usr/bin/env python3
"""Session 44 TASK 6: build demo_s44/INDEX.md.

Every value is read back from each trial's own files. The `eyeball` column is emitted as PENDING
and is never auto-filled -- Session 41's index listed all 18 screening runs as clean while the same
session's known_issues/ correctly failed 4 of 9 clips, and a column a machine cannot judge has to
say so rather than defaulting to a pass.
"""
import csv
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import s44_selftest  # noqa: E402

ROOT = "/mnt/ssd/Social_Navigation/trial_outputs/demo_s44"

# Clips whose character must hold station -- enables check 3.4, which is SKIPped otherwise.
STATIC = {"mixamo_Standing_Arguing", "mixamo_Sitting"}
# Sitting's character sits on the S44 stool, so its expected root height is the seat, not the floor.
EXPECTED_Y = {}

EXCLUDED = [
    ("talking_standing", "dropped on request (S44 5.1)"),
    ("Stroke_Shaking_Head",
     "permanently excluded -- see known_issues/S44_stroke_shaking_head_excluded.md"),
]


def load_results():
    p = os.path.join(ROOT, "results.tsv")
    if not os.path.exists(p):
        return []
    with open(p) as f:
        return [r for r in csv.DictReader(f, delimiter="\t") if r.get("out_dir")]


def clamp_cell(trial_dir):
    log = os.path.join(trial_dir, "unity.log")
    if not os.path.exists(log):
        return "-"
    worst = 0.0
    for line in open(log, errors="ignore"):
        if "[S44Clamp]" in line:
            for m in re.finditer(r"(loHits|hiHits)=\d+ \(([\d.]+) ?%\)", line):
                worst = max(worst, float(m.group(2)))
    return "none" if worst == 0.0 else "{:.1f}%".format(worst)


def gates_cell(trial_dir):
    p = os.path.join(trial_dir, "meta.json")
    if not os.path.exists(p):
        return "-"
    m = json.load(open(p))
    order = [("content", "contentGateOk"), ("aspect", "aspectGateOk"),
             ("approach", "approachGateOk"), ("trigSpd", "triggerSpeedGateOk"),
             ("overlay", "overlayOk"), ("manifest", "fileManifestGateOk")]
    return " ".join("{}{}".format(k, "+" if m.get(f) else ("**-**" if m.get(f) is False else "?"))
                    for k, f in order)


def main():
    rows = load_results()
    if not rows:
        print("no results.tsv under " + ROOT, file=sys.stderr)
        return 1

    out = [
        "# Session 44 -- demo_s44",
        "",
        "> ## FORMAT / EYEBALL VALIDATION BATCH, NOT A SAFETY CENSUS.",
        "> **N = 1 per configuration.** `min_dist` appears because the pipeline emits it and",
        "> **must not be quoted as a safety result.** This project's rule is worst-observed over",
        "> N >= 5, and Session 43's accidental control measured up to **1.4 m** of run-to-run",
        "> spread on byte-identical commands (`scared` 3.486 -> 4.890).",
        "",
        "Generated by `tools/s44_make_index.py`, reading each trial's own files.",
        "",
        "## Self-tests 3.1-3.8",
        "",
        "`PASS`/`FAIL`/`SKIP` per `tools/s44_selftest.py`. **SKIP is not PASS** -- it means the",
        "criterion did not apply to that trial (3.4 only applies to stationary clips; 3.1 needs a",
        "sustained idle period to exist).",
        "",
        "| config | 3.1 idle | 3.2 slide | 3.3 clamp | 3.4 static | 3.5 ground | 3.6 nearclip | 3.7 gates | 3.8 format | clamp | eyeball | min_dist (N=1, NOT safety) |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]

    details = []
    for r in rows:
        d = r["out_dir"]
        name = r["config"]
        res = s44_selftest.run(d, static=(name in STATIC), expected_y=EXPECTED_Y.get(name))
        by = {c["tag"]: c for c in res["checks"]}
        cells = []
        for tag in ("3.1", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8"):
            c = by.get(tag, {"status": "-"})
            s = c["status"]
            cells.append("**FAIL**" if s == "FAIL" else s)
            if s == "FAIL":
                details.append("- **{}** {} ({}): {}".format(name, tag, c["name"], c["detail"]))
        out.append("| {} | {} | {} | PENDING | {} |".format(
            name, " | ".join(cells), clamp_cell(d), r.get("min_dist", "NA")))

    out += ["", "### Gates, per trial", "",
            "`+` pass, `-` fail. Nine-gate set: the six recorded in meta.json below, plus the",
            "pre-flight output-root sentinel, disk-space and editor-lock checks, which abort before",
            "a trial directory exists and so cannot appear as a per-trial column.",
            "", "| config | exit | gates |", "|---|---|---|"]
    for r in rows:
        out.append("| {} | {} | {} |".format(r["config"], r.get("exit", "?"), gates_cell(r["out_dir"])))

    out += ["", "### Self-test failures", ""]
    out += (details if details else ["None -- every applicable check passed."])

    out += ["", "## Excluded from this batch", "", "| asset | reason |", "|---|---|"]
    for a, why in EXCLUDED:
        out.append("| `{}` | {} |".format(a, why))

    out += ["", "## Left to the eye", "",
            "These have no objective criterion and are **not** auto-filled:",
            "",
            "- `Running` -- do the legs still cross",
            "- `carry_and_walk` -- does the foot twitching still occur",
            "- `Standing_Arguing` -- does the two-person composition read naturally, is the phase",
            "  offset enough that they do not look synchronised",
            "- `Sitting` -- does the character sit on the stool convincingly",
            "- overall naturalness",
            "",
            "Watch `video/pov_full_ov.mp4` in each trial directory.", ""]

    path = os.path.join(ROOT, "INDEX.md")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote {} ({} trials, {} self-test failures)".format(path, len(rows), len(details)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
